app/urls.py
from django.urls import path

from . import views

app_name = "apk"


urlpatterns = [
    path("login", views.Login.as_view(), name="login"),
    path("logout", views.Logout.as_view(), name="logout"),

    path("", views.Index.as_view(), name="index"),
    path("change-password/", views.ChangePassword.as_view(), name="change_password"),

    path("cases/", views.Cases.as_view(), name="cases"),
    path("cases/<int:pk>/", views.CaseDetail.as_view(), name="case"),
    path("cases/<int:pk>/diary/", views.CaseDiary.as_view(), name="case_diary"),
    path("diary/", views.DEs.as_view(), name="diary"),
    
    # path("tip-off/", views.TipOff.as_view(), name="tip_off"),


]

computers/urls.py
from django.urls import path, include

from . import views

app_name = "com"

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("logs/", views.Logs.as_view(), name="logs"),
    path("logs/<int:pk>", views.LogDetail.as_view(), name="log_detail"),

    path("computers/", views.Computers.as_view(), name="computers"),
    path("computers/<int:pk>", views.ComputerDetail.as_view(), name="computer"),

    path("branches/", views.Branches.as_view(), name="branches"),
    path("branches/<int:pk>", views.BranchDetail.as_view(), name="branch_detail"),

    path("change-password/", views.ChangePwd.as_view(), name="change_password"),
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('', include('computers.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/apk/branch.html
{% extends 'base.html' %}
{% load humanize %}
{% block branches_link_active %}active{% endblock %}
{% block page_header_title %}Branch #{{br.id}} &mdash; {{br.name}}{% endblock page_header_title %}
{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-navy">
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="bg-navy">
                            <tr>
                                <th>Branch ID</th>
                                <th>Name</th>
                                <th>Created On</th>
                                <th>Last Modified</th>
                                <th>Asset Count</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% with br as b %}
                                <tr>
                                    <td>
                                        <a href="{% url 'com:branch_detail' b.pk %}">{{b.id}}</a>
                                    </td>
                                    <td>{{ b.name }}</td>
                                    <td>
                                        {{b.created}} <br>
                                        <small class="text-muted">{{ b.created|naturaltime }}</small>
                                    </td>
                                    <td>
                                        {{b.modified}}
                                    </td>
                                    <td>
                                        {{b.computers.count}}
                                    </td>
                                </tr>
                            {% endwith %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/apk/branches.html
{% extends 'base.html' %}
{% load humanize %}
{% block branches_link_active %}active{% endblock %}
{% block page_header_title %}Branch List{% endblock page_header_title %}
{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-navy">
                <div class="card-header">
                    {{ brs.count }} Branches on File
                </div>
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="bg-navy">
                            <tr>
                                <th>Branch ID</th>
                                <th>Name</th>
                                <th>Created On</th>
                                <th>Last Modified</th>
                                <th>Asset Count</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for b in brs %}
                                <tr>
                                    <td>
                                        <a href="{% url 'com:branch_detail' b.pk %}">{{b.id}}</a>
                                    </td>
                                    <td>{{ b.name }}</td>
                                    <td>
                                        {{b.created}} <br>
                                        <small class="text-muted">{{ b.created|naturaltime }}</small>
                                    </td>
                                    <td>
                                        {{b.modified}}
                                    </td>
                                    <td>
                                        {{b.computers.count}}
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="10" class="text-center">
                                        <i>No logs available at the moment</i>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/apk/case.html
{% extends 'apk/base.html' %}
{% load humanize %}
{% block cases_link_active %}active{% endblock %}
{% block page_header_title %}Case <b>#{{ case.id }}</b>{% endblock page_header_title %}
{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-navy">
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="bg-navy">
                            <tr>
                                <th>Case ID</th>
                                <th>Crime</th>
                                <th>Complainant</th>
                                <th>Plaintiff</th>
                                <th>Recorded By</th>
                                <th>Last modified</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% with case as c %}
                                <tr>
                                    <td>
                                        <a href="{% url 'apk:case' c.pk %}">{{c.id}}</a>
                                    </td>
                                    <td>{{ c.crime }}</td>
                                    <td>{{ c.complainant }}</td>
                                    <td>{{c.plaintiff }}</td>
                                    <td>
                                        {{c.logged_by}}
                                    </td>
                                    <td>
                                        {{c.modified}} <br>
                                        <small class="text-muted">
                                            {{c.modified|naturaltime}}
                                        </small>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        Assigned to Court
                                    </td>
                                    <td colspan="4">
                                       <b> {{c.court}}</b>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        ({{c.investigators.count}}) Investigator{{c.investigators|pluralize}} Assigned
                                    </td>
                                    <td colspan="4">
                                       {% for o in c.investigators.all %}
                                        <b>{{ o.name }}</b> <br>
                                       {% endfor %}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Summary
                                    </td>
                                    <td colspan="6">
                                       <i> {{c.summary}}</i>
                                    </td>
                                </tr>
                            {% endwith %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card card-outline card-navy">
                <div class="card-header">
                   <a href="{% url 'apk:case_diary' case.pk %}" class="btn btn-xs btn-warning">
                       <i class="fas fa-plus"></i> Add Entry
                   </a> Diary Entries ({{case.diary_entries.count}})
                </div>
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="bg-navy">
                            <tr>
                                <th>#</th>
                                <th>Date</th>
                                <th>Time</th>
                                <th>Notes</th>
                                <th>Last Modified</th>
                                <th>Made By</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for de in case.diary_entries.all %}
                                <tr>
                                    <td>
                                        {{forloop.counter}}
                                    </td>
                                    <td>{{ de.created|date }} <br><span class="text-muted">{{de.created|timesince }} ago.</span></td>
                                    <td>{{ de.created|time }}</td>
                                    <td>{{de.notes }}</td>
                                    <td>
                                        {{de.modified}}
                                    </td>
                                    <td>
                                        {{de.logger|default:'-'}}
                                    </td>
                                </tr>
                              
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/apk/cases.html
{% extends 'apk/base.html' %}
{% load humanize %}
{% block cases_link_active %}active{% endblock %}
{% block page_header_title %}Cases assigned to <b>{{ officer.name }}</b>{% endblock page_header_title %}
{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-navy">
                <div class="card-header">
                    {{ cases.count }} Assigned Case{{cases.count|pluralize}}
                </div>
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="bg-navy">
                            <tr>
                                <th>Case ID</th>
                                <th>Crime</th>
                                <th>Complainant</th>
                                <th>Plaintiff</th>
                                <th>Recorded By</th>
                                <th>Last modified</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for c in cases %}
                                <tr>
                                    <td>
                                        <a href="{% url 'apk:case' c.pk %}">{{c.id}}</a>
                                    </td>
                                    <td>{{ c.crime }}</td>
                                    <td>{{ c.complainant }}</td>
                                    <td>{{c.plaintiff }}</td>
                                    <td>
                                        {{c.logged_by}}
                                    </td>
                                    <td>
                                        {{c.modified}} <br>
                                        <small class="text-muted">
                                            {{c.modified|naturaltime}}
                                        </small>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="10" class="text-center">
                                        <i>Nothing available at the moment</i>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/apk/comps.html
{% extends 'base.html' %}
{% load humanize %}
{% block assets_link_active %}active{% endblock %}
{% block page_header_title %}Computer Assets Listing{% endblock page_header_title %}
{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-navy">
                <div class="card-header">
                    {{ comps.count }} Computer Asset{{comps.count|pluralize}}
                </div>
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="bg-navy">
                            <tr>
                                <th>Asset ID</th>
                                <th>Nickname</th>
                                <th>Type</th>
                                <th>Logs Recorded</th>
                                <th>Location</th>
                                <th>Last modified</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for c in comps %}
                                <tr>
                                    <td>
                                        <a href="{% url 'com:computer' c.pk %}">{{c.id}}</a>
                                    </td>
                                    <td>{{ c.nickname }}</td>
                                    <td>{{ c.type }}</td>
                                    <td>{{c.logs.count }}</td>
                                    <td>
                                        Branch ID: {{ c.branch.id }} <br>
                                        <span class="text-muted">{{ c.branch.name }}</span>
                                    </td>
                                    <td>
                                        {{c.modified}} <br>
                                        <small class="text-muted">
                                            {{c.modified|naturaltime}}
                                        </small>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="10" class="text-center">
                                        <i>Nothing available at the moment</i>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/apk/des.html
{% extends 'apk/base.html' %}
{% load humanize %}
{% block diary_link_active %}active{% endblock %}
{% block page_header_title %}Diary Entries by <b>{{ officer.name }}</b>{% endblock page_header_title %}
{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-navy">
                <div class="card-header">
                    {{ des.count }} Entries made
                </div>
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="bg-navy">
                            <tr>
                                <th>#</th>
                                <th>Case ID</th>
                                <th>Date</th>
                                <th>Last Modified</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for d in des %}
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td>
                                        <a href="{% url 'apk:case' d.docket.pk %}">{{d.docket.id}}</a> <br>
                                       <small> <a href="{% url 'apk:case' d.docket.pk %}"><small>{{d.docket.complainant}} vs {{d.docket.plaintiff }}</small></a></small>
                                    </td>
                                    <td>{{ d.created }} <br> <small class="text-muted"><b>{{d.created|naturaltime}}</b></small>
                                    <hr class="my-1">
                                    <span>Notes:</span> <br>
                                    <small class="text-muted">
                                        <span>{{d.notes|truncatechars:30}}</span>
                                    </small>
                                    </td>
                                    <td>{{d.modified }} <br> <small class="text-muted"><b>{{d.modified|naturaltime}}</b></small></td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="10" class="text-center">
                                        <i>Nothing available at the moment</i>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/apk/diary.html
{% extends 'apk/base.html' %}
{% load humanize crispy_forms_filters %}
{% block cases_link_active %}active{% endblock %}
{% block page_header_title %}Diary Entry for Case <b>#{{ case.id }}</b>{% endblock page_header_title %}
{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-navy">
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="bg-navy">
                            <tr>
                                <th>Case ID</th>
                                <th>Crime</th>
                                <th>Complainant</th>
                                <th>Plaintiff</th>
                                <th>Recorded By</th>
                                <th>Last modified</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% with case as c %}
                                <tr>
                                    <td>
                                        <a href="{% url 'apk:case' c.pk %}">{{c.id}}</a>
                                    </td>
                                    <td>{{ c.crime }}</td>
                                    <td>{{ c.complainant }}</td>
                                    <td>{{c.plaintiff }}</td>
                                    <td>
                                        {{c.logged_by}}
                                    </td>
                                    <td>
                                        {{c.modified}} <br>
                                        <small class="text-muted">
                                            {{c.modified|naturaltime}}
                                        </small>
                                    </td>
                                </tr>
                            {% endwith %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card card-outline card-navy">
                <div class="card-header">
                   <i class="fas fa-plus"></i> Add Diary Entry
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}

                        <button class="btn btn-success">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/apk/index.html
{% extends 'apk/base.html' %}
{% load humanize %}
{% block home_link_active %}active{% endblock %}
{% block page_header_title %}Welcome, <b>{{officer.name}}</b>{% endblock page_header_title %}
{% block page_content %}
<div class="row">
    <div class="col-sm-12 col-lg-4">
      <!-- small box -->
      <div class="small-box bg-warning">
        <div class="inner">
          <h3>{{ cases }}</h3>

          <p>Case{{cases|pluralize }} Assigned</p>
        </div>
        <div class="icon">
          <i class="ion ion-bag"></i>
        </div>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-sm-12 col-lg-4">
      <!-- small box -->
      <div class="small-box bg-success">
        <div class="inner">
          <h3>{{ closed }}</h3>

          <p>Closed case{{closed|pluralize}}</p>
        </div>
        <div class="icon">
          <i class="ion ion-stats-bars"></i>
        </div>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-sm-12 col-lg-4">
      <!-- small box -->
      <div class="small-box bg-danger">
        <div class="inner">
          <h3>{{ cold }}</h3>

          <p>Cold Case{{cold|pluralize}}</p>
        </div>
        <div class="icon">
          <i class="ion ion-person-add"></i>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
      <div class="col-12">
          <div class="card card-outline card-navy">
            <div class="card-header d-sm-block d-md-flex">
                <div>Latest Cases</div>
                <div class="ml-md-auto">
                  <a href="{% url 'apk:cases' %}" class="btn btn-sm btn-primary">View All</a>
                </div>
            </div>
            <div class="table-responsive">
              <table class="table table-borderless mb-0">
                  <thead class="bg-navy">
                      <tr>
                          <th>Case ID</th>
                          <th>Crime</th>
                          <th>Complainant</th>
                          <th>Plaintiff</th>
                          <th>Recorded By</th>
                          <th>Last modified</th>
                      </tr>
                  </thead>
                  <tbody>
                      {% for c in latest %}
                          <tr>
                              <td>
                                  <a href="{% url 'apk:case' c.pk %}">{{c.id}}</a>
                              </td>
                              <td>{{ c.crime }}</td>
                              <td>{{ c.complainant }}</td>
                              <td>{{c.plaintiff }}</td>
                              <td>
                                  {{c.logged_by}}
                              </td>
                              <td>
                                  {{c.modified}} <br>
                                  <small class="text-muted">
                                      {{c.modified|naturaltime}}
                                  </small>
                              </td>
                          </tr>
                      {% empty %}
                          <tr>
                              <td colspan="10" class="text-center">
                                  <i>Nothing available at the moment</i>
                              </td>
                          </tr>
                      {% endfor %}
                  </tbody>
              </table>
          </div>
          </div>
      </div>
  </div>
{% endblock %}

templates/apk/log.html
{% extends 'base.html' %}
{% block logs_link_active %}active{% endblock %}
{% block page_header_title %}Log #{{log.id }}{% endblock page_header_title %}
{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-navy">
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="bg-navy">
                            <tr>
                                <th>Entry ID</th>
                                <th>Type</th>
                                <th>Branch</th>
                                <th>Computer</th>
                                <th>File</th>
                                <th>Logging Period</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% with log as l %}
                                <tr>
                                    <td>
                                        <a href="{% url 'com:log_detail' l.pk %}">{{l.id}}</a>
                                    </td>
                                    <td>{{ l.type }}</td>
                                    <td>
                                        ID: {{ l.computer.branch.id }} <br>
                                        <span class="text-muted">{{ l.computer.branch.name }}</span>
                                    </td>
                                    <td>
                                        Serial: {{ l.computer.serial }} <br>
                                        <span class="text-muted">{{l.computer.nickname }}</span>
                                    </td>
                                    <td>
                                        <a href="{{ i.file.url }}">{{ l.file }}</a>
                                    </td>
                                    <td>
                                        {{ l.date_from }} &mdash; {{l.date_to}} <br>
                                        Duration:<span class="text-muted"> {{l.date_from|timesince:l.date_to }}</span>
                                    </td>
                                </tr>
                            {% endwith %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/apk/logs.html
{% extends 'base.html' %}
{% block logs_link_active %}active{% endblock %}
{% block page_header_title %}Log List{% endblock page_header_title %}
{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-navy">
                <div class="card-header">
                    {{ logs.count }} Log{{logs.count|pluralize}} Uploaded
                </div>
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="bg-navy">
                            <tr>
                                <th>Entry ID</th>
                                <th>Type</th>
                                <th>Branch</th>
                                <th>Computer</th>
                                <th>File</th>
                                <th>Logging Period</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for l in logs %}
                                <tr>
                                    <td>
                                        <a href="{% url 'com:log_detail' l.pk %}">{{l.id}}</a>
                                    </td>
                                    <td>{{ l.type }}</td>
                                    <td>
                                        ID: {{ l.computer.branch.id }} <br>
                                        <span class="text-muted">{{ l.computer.branch.name }}</span>
                                    </td>
                                    <td>
                                        Serial: {{ l.computer.serial }} <br>
                                        <span class="text-muted">{{l.computer.nickname }}</span>
                                    </td>
                                    <td>
                                        <a href="{{ i.file.url }}">{{ l.file }}</a>
                                    </td>
                                    <td>
                                        {{ l.date_from }} &mdash; {{l.date_to}} <br>
                                        Duration:<span class="text-muted"> {{l.date_from|timesince:l.date_to }}</span>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="10" class="text-center">
                                        <i>No logs available at the moment</i>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}